# Generated by Django 3.1.7 on 2021-04-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210414_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
